/**
 * Created by playcat on 2015/10/28.
 */


var DropDownListDefines = {
		
		PROMOTE_TYPE :'ACTIVITY_PROMOTE_TYPE',
		
		BILLING_METHOD :'BILLING_METHOD',
		
		CONTENT_TYPE:'CONTENT_TYPE',
			
		NOTICE_TYPE:'NOTICE_TYPE',
			
		APPROVE_METHOD:'APPROVE_METHOD',
		
		APPROVE_STATUS:'APPROVE_STATUS',
		
		ACTIVITY_STATUS:'ACTIVITY_STATUS',
		
		MEDIA_TYPE:'MEDIA_TYPE',
		
		MEDIA_STATUS:'MEDIA_STATUS',
			
		SITE_TYPE:'SITE_TYPE',
			
		TAX_TYPE:'TAX_TYPE',
		
		DROP_DOWN_CODE:'DROP_DOWN_CODE',
		
		PROMOTE_CODE_TYPE:'PROMOTE_CODE_TYPE',
		
		IS_NEED_INVOICE:'IS_NEED_INVOICE',
		
		COMMISSION_APPLY_STATUS:'COMMISSION_APPLY_STATUS',
		
		SETTLEMENT_STATUS:'SETTLEMENT_STATUS',

		ORDER_SETTLEMENT_STATUS:'ORDER_SETTLEMENT_STATUS',
		
		ENCOURAGE_TYPE:'ENCOURAGE_TYPE',
		
		SETTLEMENT_CONDITION:'SETTLEMENT_CONDITION',
		
		MEMBER_TYPE:'MEMBER_TYPE',
		
		ACCOUNT_TYPE:'ACCOUNT_TYPE',
		
		MEMBER_APPROVE_STATUS:'MEMBER_APPROVE_STATUS',
		
		ACCOUNT_STATUS:'ACCOUNT_STATUS',
		
		MEMBER_APPROVE_TYPE:'MEMBER_APPROVE_TYPE',
		
		ENCOURAGE_RULE_STATUS :'ENCOURAGE_RULE_STATUS',
		
		ENCOURAGE_METHOD:'ENCOURAGE_METHOD',
		
		AUDIT_RESULT:'APPROVE_RESULT',
		
		MEDIA_USE_STATUS:'MEDIA_USE_STATUS',
		
		MESSAGE_STATUS:'MESSAGE_STATUS',
		
		MESSAGE_RECEIVER_RANGE:'MESSAGE_RECEIVER_RANGE',

		//MEDIA_USE_STATUS:'MEDIA_USE_STATUS',

		ORDER_STATUS:'ORDER_STATUS',
		
		USER_MESSAGE_STATUS:'USER_MESSAGE_STATUS',
		
		MESSAGE_TYPE:'MESSAGE_TYPE',
	
		MEMBER_APPROVE_REMARK:'MEMBER_APPROVE_REMARK',

		MEDIA_APPROVE_REMARK:'MEDIA_APPROVE_REMARK',
		
		ENCOURAGE_SCOPE:'ENCOURAGE_SCOPE',
		
		ENCOURAGE_APPROVE_REMARK:'ENCOURAGE_APPROVE_REMARK',
		
		ACTIVITY_TYPE:'ACTIVITY_TYPE',
		
		ACTIVITY_APPROVE_STATUS:'ACTIVITY_APPROVE_STATUS',
		
		ORDER_PAY_STATUS:'ORDER_PAY_STATUS',
		
		ORDER_OBTAN_WAY:'ORDER_OBTAN_WAY',
		
		NOTICE_STATUS:'NOTICE_STATUS',
		
		NOTICE_IS_SEND_MSG:'NOTICE_IS_SEND_MSG',
		
		FAQ_IS_HOT_QUESTION:'FAQ_IS_HOT_QUESTION',
		
		FAQ_TYPE:'FAQ_TYPE',
		
		APPROVE_RESULT:'APPROVE_RESULT',
		
		PMS_SBOM_STATUS:'PMS_SBOM_STATUS',
		
		PMS_SALE_CHANNEL_CODE:'PMS_SALE_CHANNEL_CODE',
			
		ORDER_IMPORT_RESULT:'ORDER_IMPORT_RESULT'
		

};